<?php

# $menuEntries is an array of menu entries for this plugin
# type is an enum of status/content/output/help (main menu area)


$menuEntries = Array(
    Array(
        'text' => 'Zettle - Status',
        'type' => 'status',
        'page' => 'status.php',
        'wrap' => 1
    ),
    Array(
        'text' => 'Zettle - Setup',
        'type' => 'content',
        'page' => 'setup.php',
        'wrap' => 1
    ),
    Array(
        'text' => 'Zettle - Help',
        'type' => 'help',
        'page' => 'help.php',
        'wrap' => 1
    )
);

##############################################################################
# Display the menu entries for this plugin.
#
# It is expected that two variables are already set:
# $plugin - contains the name of the current plugin directory/repoName
# $menu - contains the name of the menu section/type
foreach ($menuEntries as $entry)
{
    if ($entry['type'] != $menu)
        continue;

    if (preg_match('/^http.?:\/\//', $entry['page']))
    {
        printf("<li><a href='%s' target='_blank'>%s</a></li>\n",
            $entry['page'], $entry['text']);
    }
    else
    {
        $nopage = '';
        if (isset($entry['wrap']) && ($entry['wrap'] == 0))
            $nopage = '&nopage=1';

        printf("<li><a href='plugin.php?plugin=%s&page=%s%s'>%s</a></li>\n",
            $plugin, $entry['page'], $nopage, $entry['text']);
    }
}
?>
